AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - bin/*

##########
# LAYOUT #
##########

Layout/LineLength:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

#########
# STYLE #
#########

Style/Documentation:
  Enabled: false

###########
# METRICS #
###########

Metrics/BlockLength:
  Enabled: false
